version: '2'
services:
  lint:
    image: koalaman/shellcheck-alpine:v0.8.0@sha256:f42fde76d2d14a645a848826e54a4d650150e151d9c81057c898da89a82c8a56
    volumes:
      - ".:/plugin:ro"
    entrypoint: sh
    command:
      - -c
      - 'shellcheck ./plugin/*.sh'

  tests:
    image: buildkite/plugin-tester:v4.1.0@sha256:cc69234d0d6dde7a0cde8e52b27be279cc5618490f932ef2497cb4bab052e08b
    volumes:
      - ".:/plugin:ro"
