version: '2'
services:
  lint:
    image: koalaman/shellcheck-alpine:v0.9.0@sha256:e19ed93c22423970d56568e171b4512c9244fc75dd9114045016b4a0073ac4b7
    volumes:
      - ".:/plugin:ro"
    entrypoint: sh
    command:
      - -c
      - 'shellcheck ./plugin/*.sh'

  tests:
    image: buildkite/plugin-tester:v4.0.0@sha256:73958fc0768b18ec691e9def050dbc25f814411c9901abfac8cd1f2f361ce8d5
    volumes:
      - ".:/plugin:ro"
