name: ci

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(toJson(github.event.commits), '[ci skip]') && !contains(toJson(github.event.commits), '[skip ci]')
    steps:
      - uses: actions/checkout@v3
      - run: make lint
      - run: make test

  release:
    needs: [test]
    # only create a release on main builds:
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout code with full history (unshallow)
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: fetch tags
        run: git fetch --force --tags

      - name: install autotag binary
        run: |
          curl -sL https://git.io/autotag-install | sudo sh -s -- -b /usr/local/bin

      - name: increment tag and create release
        run: |
          set -eou pipefail

          new_version=$(autotag -v)
          gh release create v"${new_version}"
