name: ci

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && !contains(toJson(github.event.commits), '[ci skip]') && !contains(toJson(github.event.commits), '[skip ci]')
    steps:
      - uses: actions/checkout@v3
      - run: make lint
      - run: make test
# TODO: on main branch, run autotag to bump the version and then hit the api to publish the tag (signed)
